### ISSUE TITLE
Cant get on toon

### ISSUE THREAD

**Issue by PaleAle59** [romovs/amber#128]
1.67.0.232a5e92
Windows 10 10.0 x64, 1.8.0_161 x86
NVIDIA Corporation (GeForce GT 720/PCIe/SSE2) - 4.6.0 NVIDIA 388.13

java.lang.NullPointerException
at haven.GameUI$NKeyBelt.draw(GameUI.java:1311)
at haven.Widget.draw(Widget.java:686)
at haven.Widget.draw(Widget.java:691)
at haven.GameUI.draw(GameUI.java:744)
at haven.Widget.draw(Widget.java:686)
at haven.Widget.draw(Widget.java:691)
at haven.RootWidget.draw(RootWidget.java:67)
at haven.UI.draw(UI.java:137)
at haven.HavenPanel.rootdraw(HavenPanel.java:342)
at haven.HavenPanel.run(HavenPanel.java:608)
at java.lang.Thread.run(Unknown Source)

**Comment by PaleAle59** [comment]
i can log into any other toon just fine.my main i can not i get this error and
 even if i switch to my laptop or desktop still  does the same
