### ISSUE TITLE
Opening painting menu crashes

### ISSUE THREAD

**Issue by ghandhikus** [romovs/amber#135]
```java
1.69.3.31bae0ef
Windows 10 10.0 x64, 11.0.1 amd64
NVIDIA Corporation (GeForce GTX 1070 Ti/PCIe/SSE2) - 4.6.0 NVIDIA 417.71

java.lang.RuntimeException: Delayed error in resource dyn/a1792f9db97e36d3 (v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:401)
	at haven.Resource$Pool$Queued.get(Resource.java:370)
	at DynTex.draw(dyntex.cjava:27)
	at haven.Widget.draw(Widget.java:694)
	at haven.Widget.draw(Widget.java:699)
	at haven.Window.draw(Window.java:200)
	at haven.Widget.draw(Widget.java:694)
	at haven.Widget.draw(Widget.java:699)
	at haven.GameUI.draw(GameUI.java:741)
	at haven.Widget.draw(Widget.java:694)
	at haven.Widget.draw(Widget.java:699)
	at haven.RootWidget.draw(RootWidget.java:67)
	at haven.UI.draw(UI.java:138)
	at haven.HavenPanel.rootdraw(HavenPanel.java:342)
	at haven.HavenPanel.run(HavenPanel.java:608)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: haven.Resource$LoadException: Load error in resource dyn/a1792f9db97e36d3(v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:462)
	at haven.Resource$Pool.access$1100(Resource.java:347)
	at haven.Resource$Pool$Loader.run(Resource.java:603)
	... 1 more
	Suppressed: haven.Resource$LoadException: Load error in resource dyn/a1792f9db97e36d3(v1), from cache source backed by FileCache(https://game.havenandhearth.com/hres/)
		... 4 more
		Suppressed: haven.Resource$LoadException: Load error in resource dyn/a1792f9db97e36d3(v1), from local res source
			... 4 more
			Suppressed: haven.Resource$LoadException: Load error in resource dyn/a1792f9db97e36d3(v1), from filesystem res source (res)
				... 4 more
			Caused by: java.io.FileNotFoundException: res\dyn\a1792f9db97e36d3.res (The system cannot find the path specified)
				at java.base/java.io.FileInputStream.open0(Native Method)
				at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
				at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
				at haven.Resource$FileSource.get(Resource.java:239)
				at haven.Resource$Pool.handle(Resource.java:446)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: dyn/a1792f9db97e36d3
			at haven.Resource$JarSource.get(Resource.java:251)
			at haven.Resource$Pool.handle(Resource.java:446)
			... 3 more
	Caused by: java.io.FileNotFoundException: res/dyn/a1792f9db97e36d3
		at haven.HashDirCache.fetch(HashDirCache.java:289)
		at haven.Resource$CacheSource.get(Resource.java:218)
		at haven.Resource$Pool.handle(Resource.java:446)
		... 3 more
Caused by: java.io.FileNotFoundException: https://game.havenandhearth.com/hres/dyn/a1792f9db97e36d3.res
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at haven.Resource$HttpSource.get(Resource.java:305)
	at haven.Resource$TeeSource.get(Resource.java:197)
	at haven.Resource$Pool.handle(Resource.java:446)
	... 3 more

```

**Comment by ghandhikus** [comment]
Main client bug. Closing.
