### ISSUE TITLE
Beast Ring, looking at stats crash

### ISSUE THREAD

**Issue by Tigerdemigoddess** [romovs/amber#141]
1.71.0.9bab86a6
Windows 10 10.0 x64, 1.8.0_171 amd64
NVIDIA Corporation (GeForce GTX 750 Ti/PCIe/SSE2) - 4.6.0 NVIDIA 431.60

java.lang.NullPointerException
	at haven.PUtils.imgsz(PUtils.java:35)
	at haven.CompImage$1.sz(CompImage.java:72)
	at haven.CompImage.add(CompImage.java:59)
	at haven.CompImage.add(CompImage.java:78)
	at ISlots$SItem.layout(ISlots.java:149)
	at ISlots.layout(ISlots.java:84)
	at haven.ItemInfo$Layout.render(ItemInfo.java:144)
	at haven.ItemInfo.longtip(ItemInfo.java:356)
	at haven.WItem.longtip(WItem.java:69)
	at haven.WItem.longtip(WItem.java:77)
	at haven.WItem$LongTip.<init>(WItem.java:106)
	at haven.WItem.tooltip(WItem.java:140)
	at haven.Widget.tooltip(Widget.java:1089)
	at haven.Widget.tooltip(Widget.java:1089)
	at haven.Window.tooltip(Window.java:334)
	at haven.Widget.tooltip(Widget.java:1089)
	at haven.Widget.tooltip(Widget.java:1089)
	at haven.HavenPanel.rootdraw(HavenPanel.java:373)
	at haven.HavenPanel.run(HavenPanel.java:608)
	at java.lang.Thread.run(Thread.java:748)
I get this when I look at the stats on a beast ring I dug up. But on nothing else currently,weird.

**Comment by romovs** [comment]
Fixed in v1.72.0
