### ISSUE TITLE
Can't even be outside with this error on 1.72.1

### ISSUE THREAD

**Issue by Tigerdemigoddess** [romovs/amber#142]
1.72.1.26512d4a
Windows 10 10.0 x64, 1.8.0_171 amd64
NVIDIA Corporation (GeForce GTX 750 Ti/PCIe/SSE2) - 4.6.0 NVIDIA 436.02

java.lang.NoSuchMethodError: haven.res.lib.tree.Tree.<init>(Lhaven/Sprite$Owner;Lhaven/Resource;FII)V
	at haven.res.lib.tree.Factory.create(tree.cjava:181)
	at haven.res.lib.tree.Factory.create(tree.cjava:169)
	at haven.Sprite.create(Sprite.java:134)
	at haven.ResDrawable.init(ResDrawable.java:55)
	at haven.ResDrawable.setup(ResDrawable.java:62)
	at haven.Gob.setup(Gob.java:564)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView.addgob(MapView.java:668)
	at haven.MapView$Gobs$GobSet.setup(MapView.java:745)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView$Gobs.setup(MapView.java:889)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView.setup(MapView.java:996)
	at haven.PView$1.setup(PView.java:206)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.setup(RenderList.java:197)
	at haven.PView.draw(PView.java:230)
	at haven.MapView.draw(MapView.java:1423)
	at haven.Widget.draw(Widget.java:715)
	at haven.Widget.draw(Widget.java:720)
	at haven.GameUI.draw(GameUI.java:741)
	at haven.Widget.draw(Widget.java:715)
	at haven.Widget.draw(Widget.java:720)
	at haven.RootWidget.draw(RootWidget.java:67)
	at haven.UI.draw(UI.java:138)
	at haven.HavenPanel.rootdraw(HavenPanel.java:343)
	at haven.HavenPanel.run(HavenPanel.java:612)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Tigerdemigoddess** [comment]
Downgraded to 1.72.0 an still can't get in game now.

**Comment by romovs** [comment]
This has been fixed in 1.72.2
