### ISSUE TITLE
Warning Error when running sh file in terminal!

### ISSUE THREAD

**Issue by xhodan** [romovs/amber#143]
```
xhodan@DT-1-2019:~/Desktop/Haven & Hearth Amber$ sh run.sh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/xhodan/Desktop/Haven%20&%20Hearth%20Amber/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
xhodan@DT-1-2019:~/Desktop/Haven & Hearth Amber$ 
```

No idea what this is all about... anyone able to help?

**Comment by vlopp** [comment]
Same happens for Purus Pasta client, should it be of any importance.

**Comment by vlopp** [comment]
Also, a similar error on my side.

```
rijndael@rd:~/Downloads/amber-1.77.1$ ./run.sh
java.io.FileNotFoundException: grid_ids.txt (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at haven.Config.<clinit>(Config.java:621)
        at haven.MainFrame.<clinit>(MainFrame.java:41)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/home/rijndael/Downloads/amber-1.77.1/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!

``

**Comment by vlopp** [comment]
Fixed by running the client with Java 8.

8 is *required*. any version higher will produce the above.
