### ISSUE TITLE
Doesn't run on MacOs Catalina 

### ISSUE THREAD

**Issue by StepanKuksenko** [romovs/amber#163]
I can't run the client on MacNook Pro with MacOS Catalina 
I have latest Java 8 update 221 x64 and JDK

The error:

```
❯ ./run.command
java.io.FileNotFoundException: grid_ids.txt (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:212)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:154)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:109)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at haven.Config.<clinit>(Config.java:640)
	at haven.MainFrame.<clinit>(MainFrame.java:41)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jogamp.opengl.awt.Java2D$2 (file:/Users/stepan.kuksenko/Desktop/amber/jogl.jar) to field sun.java2d.opengl.OGLUtilities.UNDEFINED
WARNING: Please consider reporting this to the maintainers of jogamp.opengl.awt.Java2D$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-04-19 23:59:11.833 java[47508:774383] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff38990d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff716b45bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff389b950c -[NSException raise] + 9
	3   AppKit                              0x00007fff35bc024c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff35ba7cb2 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff35ba7723 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libnativewindow_macosx.jnilib       0x0000000133fc877e Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 382
	7   ???                                 0x00000001183366b0 0x0 + 4700989104
)
libc++abi.dylib: terminating with uncaught exception of type NSException
./run.command: line 3: 47508 Abort trap: 6           java -Xss1024k -Xms512m -Xmx1024m -jar hafen.jar -U https://game.havenandhearth.com/hres/ game.havenandhearth.com
```

**Comment by StepanKuksenko** [comment]
if i can help with with something else...tell me

**Comment by Toggie** [comment]
try installing and using java 9.  I have no idea why this was exactly my error and using java 9 fixed it.
