### ISSUE TITLE
Exception from chick bones??

### ISSUE THREAD

**Issue by aldrin233** [romovs/amber#165]
`1.79.0.556d3a56
Windows 10 10.0 x64, 1.8.0_242 amd64
NVIDIA Corporation (GeForce GTX 1060/PCIe/SSE2) - 4.6.0 NVIDIA 445.87

java.lang.RuntimeException: Bone "" in animation reference does not exist in skeleton Skeleton(gfx/kritter/chicken/chick)
	at haven.Skeleton$ResPose.iaIaCthulhuFhtagn(Skeleton.java:954)
	at haven.Skeleton$ResPose.access$1000(Skeleton.java:846)
	at haven.Skeleton$ResPose$ResMod.<init>(Skeleton.java:962)
	at haven.Skeleton$ResPose.forskel(Skeleton.java:979)
	at haven.Skeleton$ModFactory$1.create(Skeleton.java:512)
	at haven.Skeleton.mkposemod(Skeleton.java:528)
	at haven.Composite.loadposes(Composite.java:81)
	at haven.Composite.ctick(Composite.java:115)
	at haven.Gob.ctick(Gob.java:231)
	at haven.OCache.ctick(OCache.java:115)
	at haven.Glob.ctick(Glob.java:157)
	at haven.HavenPanel.run(HavenPanel.java:637)
	at java.lang.Thread.run(Thread.java:821)`

**Comment by aldrin233** [comment]
Opening vanilla client and loading the map fixes the issue.

**Comment by aldrin233** [comment]
> Opening vanilla client and loading the map fixes the issue.

Edit : Does not fix it, i thought it got fixed but the fix seems to only work when moving away from the spot were the crash happens
