### ISSUE TITLE
AccessDeniedException: .\data\cache3871586981928922514.new

### ISSUE THREAD

**Issue by ghandhikus** [romovs/amber#44]
1.46.0:85e027b8a2da4f38a08a4711c56086b747686092

java.lang.RuntimeException: Delayed error in resource paginae/act/tracking (v4), from forking source backed by HTTP res source (http://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:352)
	at haven.Resource$Pool$Queued.get(Resource.java:321)
	at haven.Glob$Pagina.res(Glob.java:150)
	at haven.Glob$Pagina.act(Glob.java:154)
	at haven.MenuGrid.cons(MenuGrid.java:93)
	at haven.MenuGrid.updlayout(MenuGrid.java:146)
	at haven.MenuGrid.tick(MenuGrid.java:424)
	at haven.Widget.tick(Widget.java:651)
	at haven.Widget.tick(Widget.java:651)
	at haven.GameUI.tick(GameUI.java:678)
	at haven.Widget.tick(Widget.java:651)
	at haven.UI.tick(UI.java:136)
	at haven.HavenPanel.run(HavenPanel.java:580)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource paginae/act/tracking(v4), from forking source backed by HTTP res source (http://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:409)
	at haven.Resource$Pool.access$1100(Resource.java:298)
	at haven.Resource$Pool$Loader.run(Resource.java:550)
	... 1 more
Caused by: java.nio.file.AccessDeniedException: C:\Users\Daniel\AppData\Roaming\Haven and Hearth\data\cache3871586981928922514.new -> C:\Users\Daniel\AppData\Roaming\Haven and Hearth\data\44c862dde41c23ab.0
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at haven.HashDirCache$2.close(HashDirCache.java:234)
	at haven.StreamTee.close(StreamTee.java:51)
	at haven.Resource$Pool.handle(Resource.java:402)
	... 3 more

**Comment by ghandhikus** [comment]
Happened for the first time after launching haven, by pressing Create Character button

**Comment by ghandhikus** [comment]
1.46.0:85e027b8a2da4f38a08a4711c56086b747686092

java.lang.RuntimeException: Delayed error in resource gfx/terobjs/items/rowanberry (v2), from forking source backed by HTTP res source (http://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:352)
	at haven.Resource$Pool$Queued.get(Resource.java:321)
	at haven.TexGL$$tex$1.resolve(TexGL.java:439)
	at haven.Material$Res.get(Material.java:259)
	at haven.StaticSprite.lsparts(StaticSprite.java:65)
	at haven.StaticSprite.<init>(StaticSprite.java:57)
	at haven.res.lib.tree.Tree.<init>(tree.cjava:11)
	at haven.res.lib.tree.Tree.<init>(tree.cjava:20)
	at sun.reflect.GeneratedConstructorAccessor27.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at haven.Utils.construct(Utils.java:1307)
	at haven.Sprite$2.create(Sprite.java:86)
	at haven.Sprite.create(Sprite.java:128)
	at haven.ResDrawable.init(ResDrawable.java:54)
	at haven.ResDrawable.setup(ResDrawable.java:59)
	at haven.Gob.setup(Gob.java:481)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView.addgob(MapView.java:669)
	at haven.MapView$Gobs$GobSet.setup(MapView.java:749)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView$Gobs.setup(MapView.java:893)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.add(RenderList.java:247)
	at haven.MapView.setup(MapView.java:994)
	at haven.PView$1.setup(PView.java:206)
	at haven.RenderList.setup(RenderList.java:170)
	at haven.RenderList.setup(RenderList.java:197)
	at haven.PView.draw(PView.java:230)
	at haven.MapView.draw(MapView.java:1430)
	at haven.Widget.draw(Widget.java:677)
	at haven.Widget.draw(Widget.java:682)
	at haven.GameUI.draw(GameUI.java:652)
	at haven.Widget.draw(Widget.java:677)
	at haven.Widget.draw(Widget.java:682)
	at haven.RootWidget.draw(RootWidget.java:67)
	at haven.UI.draw(UI.java:141)
	at haven.HavenPanel.rootdraw(HavenPanel.java:333)
	at haven.HavenPanel.run(HavenPanel.java:589)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource gfx/terobjs/items/rowanberry(v2), from forking source backed by HTTP res source (http://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:409)
	at haven.Resource$Pool.access$1100(Resource.java:298)
	at haven.Resource$Pool$Loader.run(Resource.java:550)
	... 1 more
Caused by: java.nio.file.AccessDeniedException: C:\Users\Daniel\AppData\Roaming\Haven and Hearth\data\cache8066724453146820986.new -> C:\Users\Daniel\AppData\Roaming\Haven and Hearth\data\33fab70bf58847ed.0
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at haven.HashDirCache$2.close(HashDirCache.java:234)
	at haven.StreamTee.close(StreamTee.java:51)
	at haven.Resource$Pool.handle(Resource.java:402)
	... 3 more
