### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by ghandhikus** [romovs/amber#47]
There is no information on how can I contribute to the project. I'd like to add some features and optimize the client but I can't figure out which Main method to run. I've tried to launch MainFrame and a few more. Can you contact me through the discord? https://discord.gg/7TJWC7C My nick there is Ghandhi
```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at haven.MainFrame.<clinit>(MainFrame.java:41)
Caused by: java.lang.NullPointerException
	at haven.Resource.loadtex(Resource.java:1733)
	at haven.Config$8.<init>(Config.java:330)
	at haven.Config.<clinit>(Config.java:329)
	... 1 more
```

**Comment by romovs** [comment]
Ok got it installed.
Closing this issue for now. Feel free to reopen if needed.
