### ISSUE TITLE
An error has occurred! Please notify the client developer.

### ISSUE THREAD

**Issue by khumarahn** [romovs/amber#51]
Hi, I am getting the following error on start of the client:

```
1.50.0:ac687c0c39c49916065ddbff964b4708662fcb86

java.lang.OutOfMemoryError: Java heap space
	at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
	at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
	at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:77)
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:721)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at haven.UpdateChecker.getjson(UpdateChecker.java:35)
	at haven.UpdateChecker.run(UpdateChecker.java:17)
```

I'm on linux, java in use is icedtea. Things used to work fine some time ago, but stopped after a system update which did not involve java itself. Maybe it is because of nss update? I would be happy to provide more info, but it isn't clear what.

**Comment by romovs** [comment]
What nss & icedtea versions are you currently using?

**Comment by khumarahn** [comment]
nss-3.28.1, and icedtea-3.2.0

**Comment by romovs** [comment]
Looks like a bug in OpenJDK JVM.
I couldn't test with NSS 3.28.1 specifically since it's a bit problematic to install on my distribution. But NSS 3.27.0 and JVM 1.8.0.111 (x64) works fine here.
Verify that you are running latest JVM `java -version` - 1.8.0.111. If that's already the case I would suggest taking it up with the OpenJDK developers[1]

As a workaround you could just remove haven.UpdateChecker as it's only used for checking for new releases and not strictly required.


[1]: Simplified test case. Not tested.

```
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class Test {
    public Test() {
        try {
            InputStream is = new URL("https://api.github.com").openStream();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by khumarahn** [comment]
my java version:
```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (IcedTea 3.2.0) (Gentoo icedtea-3.2.0)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```

I can use oracle's java as a workaround (and yes, it works), but would prefer to use icedtea.

**Comment by khumarahn** [comment]
I am new to java (and generally afraid of it), but tried to run the test case, and got this:
```
~/temp $ cat Test.java 
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class Test {
    public Test() {
        try {
            InputStream is = new URL("https://api.github.com").openStream();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    public static void main(String[] args) {
        Test t;
        t = new Test();
    }
}
~/temp $ javac Test.java
~/temp $ java Test
javax.net.ssl.SSLException: java.security.ProviderException: java.lang.NegativeArraySizeException
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at Test.<init>(Test.java:8)
	at Test.main(Test.java:15)
Caused by: java.security.ProviderException: java.lang.NegativeArraySizeException
	at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:147)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:703)
	at sun.security.ssl.ECDHCrypt.<init>(ECDHCrypt.java:77)
	at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:721)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:281)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	... 9 more
Caused by: java.lang.NegativeArraySizeException
	at sun.security.ec.ECKeyPairGenerator.generateECKeyPair(Native Method)
	at sun.security.ec.ECKeyPairGenerator.generateKeyPair(ECKeyPairGenerator.java:128)
	... 18 more
~/temp $ java Test
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f466cace774, pid=32317, tid=0x00007f466d129700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.2.0
# Distribution: Gentoo Base System release 2.2, package Gentoo icedtea-3.2.0
# Problematic frame:
# C  [libc.so.6+0x122774]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# ~/temp/hs_err_pid32317.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
Aborted
```
`~/temp/hs_err_pid32317.log` is here: http://pastebin.com/NC7VJGKz

strange things here, yes

**Comment by romovs** [comment]
Could you test whether this fails as well? If it does, I think it would be better to open a bug report with OpenJDK (or perhaps with NSS and/or OpenJDK maintainer of your distro in case they did any custom patches)

```bash
javac Test.java
java -cp . Test
```

Test.java
```java
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

public class Test {
    public static void main(final String[] args) {
        try {
            InputStream is = new URL("https://api.github.com").openStream();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("Done.");
    }
}
```

**Comment by khumarahn** [comment]
yes, also fails:
```
~temp $ java -cp . Test
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5722834774, pid=1893, tid=0x00007f5722e8f700
#
# JRE version: OpenJDK Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.111-b14 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.2.0
# Distribution: Gentoo Base System release 2.2, package Gentoo icedtea-3.2.0
# Problematic frame:
# C  [libc.so.6+0x122774]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# ~/temp/hs_err_pid1893.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   http://icedtea.classpath.org/bugzilla
#
Aborted
```

I'll open a bug report in gentoo. I don't really understand anything of what's going on, but maybe they will know.

**Comment by khumarahn** [comment]
the bug report seems to exist already:
https://bugs.gentoo.org/show_bug.cgi?id=605430
:-)

**Comment by romovs** [comment]
Since this is a third party issue and it's already being addressed by Gentoo developers I'll go ahead and close this one. Feel free to reopen if the problem persists in the future.
