### ISSUE TITLE
Cannot launch Amber's Client

### ISSUE THREAD

**Issue by Spriithy** [romovs/amber#52]
Hey guys, I've played H&H a while back and wanted to get back to it :) So I went here to download the latest version of your Client (that I used to have before). Yet I'm facing a quite intriguing issue. When I run the `run.bat` file Java throws me a couple of exceptions and the client holds (unresponsive). (error message pasted below).

If anyone had an idea on how to fix this, I would really appreciate it :)

Have a nice one !

```
1.54.1:958909e4b79a06f06cdada0820359ae3ae45c3fc

java.lang.RuntimeException: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel$6.uglyjoglhack(HavenPanel.java:505)
	at haven.HavenPanel$6.run(HavenPanel.java:517)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at haven.HavenPanel.redraw(HavenPanel.java:436)
	at haven.HavenPanel$1.display(HavenPanel.java:129)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: haven.GLConfig$HardwareException: Graphics context does not support programmable shading.
	at haven.GLConfig.assertcaps(GLConfig.java:83)
	at haven.GLConfig.fromgl(GLConfig.java:117)
	at haven.HavenPanel$1.init(HavenPanel.java:135)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:601)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:623)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1254)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1101)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at javax.media.opengl.Threading.invoke(Threading.java:193)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:582)
	at sun.awt.RepaintArea.paintComponent(Unknown Source)
	at sun.awt.RepaintArea.paint(Unknown Source)
	at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	... 9 more
```

**Comment by romovs** [comment]
That's due to the recent NVIDIA driver update. Try either downgrading the drivers to previous version or updating to newest. The update they released yesterday supposedly fixes this issue, although I haven't verified it.

**Comment by romovs** [comment]
There was no reply from the OP in a while. Marking as resolved. Feel free to reopen if still relevant.

**Comment by Qeeet** [comment]
I've got similar issue. My laptop is ThinkPad T420 with intel HD 3000 graphics. Original client works perfectly.
```
``1.67.11.f933e0ef
Windows 10 10.0 x64, 1.8.0_66 amd64
Microsoft Corporation (GDI Generic) - 1.1.0

java.lang.RuntimeException: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel$6.uglyjoglhack(HavenPanel.java:524)
	at haven.HavenPanel$6.run(HavenPanel.java:536)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at haven.HavenPanel.redraw(HavenPanel.java:455)
	at haven.HavenPanel$1.display(HavenPanel.java:132)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: haven.GLConfig$HardwareException: Graphics context does not support programmable shading.
	at haven.GLConfig.assertcaps(GLConfig.java:83)
	at haven.GLConfig.fromgl(GLConfig.java:117)
	at haven.HavenPanel$1.init(HavenPanel.java:149)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:601)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:623)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1254)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1101)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at javax.media.opengl.Threading.invoke(Threading.java:193)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:582)
	at sun.awt.RepaintArea.paintComponent(Unknown Source)
	at sun.awt.RepaintArea.paint(Unknown Source)
	at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	... 9 more

```
