### ISSUE TITLE
Hi your client on Asus X501a ur client don't work. Normal H&H client works fine 

### ISSUE THREAD

**Issue by JoeDoePL** [romovs/amber#55]
1.57.1:f9d98a4a8ba90d613be395cb2c9fde826ec26596

java.lang.RuntimeException: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel$6.uglyjoglhack(HavenPanel.java:505)
	at haven.HavenPanel$6.run(HavenPanel.java:517)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception occurred during init but was somehow discarded
	at haven.HavenPanel.redraw(HavenPanel.java:436)
	at haven.HavenPanel$1.display(HavenPanel.java:129)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: haven.GLConfig$HardwareException: Graphics context does not support programmable shading.
	at haven.GLConfig.assertcaps(GLConfig.java:83)
	at haven.GLConfig.fromgl(GLConfig.java:117)
	at haven.HavenPanel$1.init(HavenPanel.java:135)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:601)
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:623)
	at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:1254)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1101)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at javax.media.opengl.Threading.invoke(Threading.java:193)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:582)
	at sun.awt.RepaintArea.paintComponent(Unknown Source)
	at sun.awt.RepaintArea.paint(Unknown Source)
	at sun.awt.windows.WComponentPeer.handleEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	... 9 more

**Comment by romovs** [comment]
What Windows version do you have?
And which CPU?

**Comment by JoeDoePL** [comment]
which the badest on b820
celeron


2017-05-15 21:09 GMT+02:00 Roman Ovseitsev <notifications@github.com>:

**Comment by romovs** [comment]
Install Java **8u25** from here http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html 
`jre-8u25-windows-x64.exe` specifically if you're running 64-bit Windows.
And disable automatic updates in Java control panel afterwards.

If that doesn't help, try updating video drivers.

**Comment by JoeDoePL** [comment]
Hey you are awesome men work perfectly fine now ty for help closing an issue
